Gilnaa/memoffset

src/span_of.rs
Hi!  First of all, thank you for maintaining this extremely useful library!
Currently, `memoffset` is used by [`crossbeam-epoch`](https://github.com/crossbeam-rs/crossbeam-epoch), which is a concurrency library.  We Crossbeam developers aim to [push it](https://github.com/rayon-rs/rayon/pull/480) to [`rayon`](https://github.com/rayon-rs/rayon), which is a parallelism library.
But `rayon` should support Rust 1.12, and `memoffset` currently doesn't.  May I ask if you could merge this PR so that `memoffset` can be compiled in Rust 1.12.1, and in turn `rayon` can depend on `crossbeam-epoch`?
=> Support Rust 1.12.1

src/lib.rs, src/offset_of.rs, src/span_of.rs
Parse `expr`s using lambda like syntax to avoid recursion.
=> Support const expr (but not const fns) and arbitrary expressions

src/lib.rs, src/offset_of.rs, src/span_of.rs
Fix span_of in two ways: no more `mem::uninitialized`, and protect against deref coercions. This unfortunately has to drop support for nested fields and arrays, just like for `offset_of`.
Also share some code with offset_of, and update documentation.
=> Fix span_of

.travis.yml, Cargo.toml, README.md, build.rs, src/lib.rs, src/offset_of.rs
Includes https://github.com/Gilnaa/memoffset/pull/8.
I am also trying to lower the minimal Rust version to 1.20, as I cannot figure out why it was raised to 1.25.
=> Fix README and lower minimum Rust version

src/offset_of.rs
This is an important aspect of any `offset_of` macro, so it is worth calling out explicitly here.
=> explain why we do not have deref coercion problems

src/lib.rs
The current implementation doesn't work in const code at all (since #11), if I'm not mistaken. This PR updates the library doc comment to reflect that.
=> Update library documentation to reflect removal of const implementation.

src/offset_of.rs, src/span_of.rs
This allows name paths with :: to be passed in.
=> Change the struct parameter from a tt to a path.

build.rs, src/lib.rs
Tested with nightly-2017-09-01 which was just after 1.20 was released.
The 1.40 version comparison currently **doesn't work**, since the nightly 1.40 compiler equates lower than `Version::from((1, 40, 0))`. This shouldn't be a problem once 1.41 nightly compilers are available.
=> Fixed build for old nightlies where doctests were not present.

README.md, src/lib.rs, src/offset_of.rs
Expose the part of `offset_of!` that computes a raw pointer to a field as a separate macro.
@Diggsey [expressed](https://github.com/Diggsey/rust-field-offset/pull/3) that this would be interesting for their crate.
If rust-field-offset could depend on memoffset to use this macro, that would mean there is just one place we have to change once `&raw` (or an equivalent mechanism) becomes stable, so that everyone uses the blessed way to do this.
@Diggsey does this macro fit the needs of your crate?
@Gilnaa are you okay with adding this to the API surface of `memoffset`?
=> add raw_field macro to compute raw ptr to field

.travis.yml, Cargo.toml, README.md, ci/miri.sh, src/lib.rs, src/offset_of.rs
With https://github.com/rust-lang/rust/issues/73394 available on nightly, we can finally provide an actually UB-free version of `offset_of!`. :)
=> add support for using raw_ref macros

.travis.yml, ci/miri.sh, src/lib.rs, src/offset_of.rs, src/raw_field.rs, src/span_of.rs
* Move `raw_field!` to its own file, and extract the "create raw ptr" part into a sub-macro so that all the rest of the code can be shared.
* Use `raw_field!` in `span_of!`. This means we do not even need the field check as a separate macro any more.
* Extract the ptr-diff computation in a sub-macro so that `offset_of!` is always the same macro, just its sub-macros differ depending on compiler version and feature flags.
=> some reorganization

README.md, src/lib.rs, src/offset_of.rs
`const_transmute` seems to have been stabilized on current nightly, see https://github.com/rust-lang/rust/pull/72920. This caused an unrecognized feature flag error when compiling against nightly.
=> Remove const_transmute feature dependency

README.md, src/lib.rs, src/offset_of.rs
With https://github.com/rust-lang/rust/pull/75250 having landed, we can finally get rid of the `transmute` here.
=> use MaybeUninit::as_ptr instead of transmute

Cargo.toml, README.md, build.rs, src/lib.rs, src/raw_field.rs
Since Rust 1.51.0, support for macro addr_of!() has been stabilized[1],
and this provides a way to get a raw pointer without potential UB in
some cases.
Memoffset alreadly uses the feature at the pre-stablilized stage (the
macro was named as raw_const then). Therefore, switch to use the
stablilized version (and name) and remove the out-dated version, also
remove the related feature gate.
[1]: https://github.com/rust-lang/rust/pull/72279
Signed-off-by: Boqun Feng <boqun.feng@gmail.com>
=> Use stablilized addr_of macro

src/offset_of.rs, src/raw_field.rs
In particular, `raw_field!` is a publicly exposed macro, and it could be used to execute `unsafe` operations without clients writing an unsafe block.
=> avoid putting user code inside unsafe blocks

.travis.yml, src/lib.rs, src/offset_of.rs, src/raw_field.rs, src/span_of.rs
Fixes https://github.com/Gilnaa/memoffset/issues/52
While at it I also fixed some minor things:
- rename `_memoffset_offset_from macro` to reflect that it is unsafe to call (internal macro, so this is not semver-breaking)
- test all versions on Travis that are significant in build.rs
=> Make span_of sound

README.md, src/lib.rs, src/offset_of.rs
Fixes https://github.com/Gilnaa/memoffset/issues/37
While at it I also removed `ptr_offset_from` since that feature is stable for a while already.
=> update feature flags and docs for const offset_of

README.md
See https://github.com/rust-lang/rust/issues/84510 -- the `const_fn` feature gate does not actually do anything any more and will be removed soon.
=> the const_fn compiler feature is a NOP

README.md, src/lib.rs
This PR removes some of `#![feature(...)]`s for compatibility with the latest nightly compiler.
- `const_maybe_uninit_as_ptr` has been stabilized by <https://github.com/rust-lang/rust/pull/90896> and is not recognized by the compiler anymore.
- `const_raw_ptr_deref` has been stabilized by <https://github.com/rust-lang/rust/pull/89551>.
=> Fix `unstable_const` for the latest compiler

src/raw_field.rs
This PR fixes `offset_of_tuple!` causing clippy warnings in consumer code.
```
warning: this pattern is unneeded as the `..` pattern can match that element
--> src/raw_field.rs:74:14
|
74  |         let (_, ..): $type;
|              ^^^ help: remove it
|
::: src/lib.rs:101:9
|
101 |         offset_of_tuple!((i32, f32, u8), 1)
|         ----------------------------------- in this macro invocation
|
= note: `#[warn(clippy::unneeded_wildcard_pattern)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unneeded_wildcard_pattern
= note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
=> Suppress `clippy::unneeded_wildcard_pattern`

src/offset_of.rs, src/raw_field.rs
Closes https://github.com/Gilnaa/memoffset/issues/66
Note that the matcher for union type is `$parent:path` all throughout; otherwise you get `error: expected identifier, found STRUCT_NAME` when attempting to expand the macro.
I have to admit I'm not sure what's the significance of this. (Original offset_of uses `:path`, tuple uses `:ty`)
=> Support unions in offset_of(_union)

src/raw_field.rs
Ticket:
- https://github.com/Gilnaa/memoffset/issues/23
The compilation failures look like this: (after applying [this](https://github.com/Gilnaa/memoffset/pull/68#discussion_r991552583) suggestion)
```
successes:
---- src/raw_field.rs - raw_field::_memoffset__field_check_tuple (line 82) stdout ----
error[E0308]: mismatched types
--> src/raw_field.rs:85:1
|
6 | _memoffset__field_check_tuple!(i32, 0);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---^^^^
| |                              |
| |                              expected due to this
| expected `i32`, found tuple
|
= note: expected type `i32`
found tuple `(_,)`
= note: this error originates in the macro `_memoffset__field_check_tuple` (in Nightly builds, run with -Z macro-backtrace for more info)
error: aborting due to previous error
For more …
```
=> Add some compile-fail tests.

.github/workflows/ci.yml, README.md, build.rs, src/lib.rs, src/offset_of.rs
When running on a compiler newer than 1.65,
automatically enable usage of the macro in const contexts.
Closes https://github.com/Gilnaa/memoffset/issues/4
Though we'll have to open a new one to track const-usage with cells.
=> Automatically enable const evaluation

Cargo.toml, src/lib.rs, src/offset_of.rs
Add a cargo feature `unstable_offset_of` to use the unstable [`core::mem::offset_of!()`](https://doc.rust-lang.org/nightly/core/mem/macro.offset_of.html) macro (https://github.com/rust-lang/rust/issues/106655). This allows for unsized structs (#25) and many other things. It also helps with [testing](https://github.com/rust-lang/rust/issues/106655#issuecomment-1548916780) of the upstream `offset_of` macro: testing is now as easy as enabling this feature, one doesn't have to change the usages from `memoffset::offset_of` to `core::mem::offset_of`.
=> Add unstable_offset_of feature to use the unstable offset_of macro

src/offset_of.rs
This code is for tests and is to line up and draw attention to the offsets. Better to suppress than eliminate.
=> clippy: Suppress `identity_op` lint.
